version: '3.6'
services:
    frontend:
        image: 192.168.43.253:5000/${VERSION}
        ports:
          - "81:80"
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
